### ISSUE TITLE
Add more encounters

### ISSUE THREAD

**Issue by ambiguousname** [BinaryByte/TC-OS-MPIA#10]
We need to add more encounters then just bandits and caves.
- [x] Add more encounters to the game in Travel.js
- [x] Add Rock Concert Encounter
- [x] Add Magic Cave Encounter
- [x] Add Bandit Wrestling Encounter
- [x] Add Cheese throwing contest Encounter
- [x] Put changes in Version 0.2 branch
- [x] Get someone to review the code

Can someone review my code? All of it is under Travel.js.

**Comment by ghost** [comment]
I reviewed it, wasn't sure exactly how everything worked, but it all fit together nicely
