### ISSUE TITLE
The game doesn't work with document.innerHTML anymore.

### ISSUE THREAD

**Issue by ambiguousname** [BinaryByte/TC-OS-MPIA#11]
Solutions anyone? I'll try to run it with JSLint and see if I get anything.

**Comment by ghost** [comment]
does doing edit() work?

**Comment by ghost** [comment]
i'm confused, when I downloaded the 2.0 branch the mpia just linked to a jsbin file... is that how it's supposed to work?

**Comment by ghost** [comment]
it seems like the mpia isn't even in the tcos files, it just links to a jsbin tab, even in the newest version of mpia.

**Comment by ambiguousname** [comment]
No. document.innerHTML doesn't work for some reason, but document.body.innerHTML does. Which means I have to add a .body to every single .innerHTML thing. Shouldn't be too hard. Just a search and replace.

**Comment by ambiguousname** [comment]
That was a reply to a previous comment. Just finish up your code and don't add anything new, so I can fix this.

**Comment by ambiguousname** [comment]
Alright, I managed to fix it. document.body.innerHTML seems to work.
