### ISSUE TITLE
Implement Noah's Encounters into the Explore function in Argo and Judal

### ISSUE THREAD

**Issue by ambiguousname** [BinaryByte/TC-OS-MPIA#13]
- [x] I need someone to review my code. It's in Argo.js, in line 24.
- [x] I need to input the code for religion()
- [x] I need to help Noah with the sewer quest battle code
- [x] I need to add the Judal Store and a Judal Explore button

**Comment by ghost** [comment]
I saw the code, it looked good, but I didn't have time to test it, also there is another encounter now, religion()

**Comment by ghost** [comment]
i made judalStore()
