### ISSUE TITLE
Judal Story Elements, Jungle Travel

### ISSUE THREAD

**Issue by ghost** [BinaryByte/TC-OS-MPIA#15]
pressing the leave button does nothing.
- [x] Fix the leave button
- [x] Fix the Town Square button

**Comment by ambiguousname** [comment]
Sort of fixed it. Need someone to go over the code.

**Comment by ghost** [comment]
I reviewed it, looks good, but maybe add buttons to either go to 'nok' or 'argo'

**Comment by ghost** [comment]
when you get to judal, clicking "town square" after the banquet gives an undefined

**Comment by ambiguousname** [comment]
I fixed it almost entirely, just need to now add the option to go to Nok.

**Comment by ambiguousname** [comment]
Done!
