### ISSUE TITLE
Improved CSS

### ISSUE THREAD

**Issue by ambiguousname** [BinaryByte/TC-OS-MPIA#6]
Can someone improve the CSS for everything in the main html file?
- [x] Go to TC-OSMPIA.html
- [x] Improve the CSS so everything looks nice
- [x] Keep in the Comic Sans MS, because A. I'm evil, and B. There's a joke in there. Seriously. Go to [JS Bin](https://jsbin.com/yejoxoxexo) and click the text with comic sans MS in it.
- [x] Put changes into the Version 0.2 branch.

**Comment by niscool** [comment]
whoops

**Comment by niscool** [comment]
where do I find the tc-os mpia files?

**Comment by niscool** [comment]
how do I edit the css? do I make a css tag that I put my .button stuff under? SO CONFUSED? I dont want to mess anything up.

**Comment by ambiguousname** [comment]
Alright, let me help you. W3 Schools provides CSS help: [W3 Schools](http://www.w3schools.com/css/)
The TC-OS MPIA files are under the Code icon. Once you load that up, there should be a button with the word branch on it. Click on it, and click Version 0.2. Once you have that loaded up, click on the TC-OSMPIA.html file, and click the pencil icon to edit it. The <style> tag is where you make the changes to 

Examine the W3 Schools CSS 

Do what you can with the CSS.

Follow the instruction above

And remember, if you feel like you've messed anything up, i can revert changes.

**Comment by ghost** [comment]
i'm just not going to do anything until i'm with you so you can show me

**Comment by ambiguousname** [comment]
Okay. Just take a look at the CSS tutorial, and get some idea of what to do.
