### ISSUE TITLE
Add more to Argo, Judal, and Nok

### ISSUE THREAD

**Issue by ambiguousname** [BinaryByte/TC-OS-MPIA#9]
Currently, there's practically nothing in our towns. We need to add more. 
- [x] Add more code to Argo.js, and make more stuff to do.
- [x] Cat Encounter
- [x] Sewer Quest 
- [x] Religion Encounter
- [x] Add more code to Nok.js, and make more stuff to do there.
- [x] A construction team is building a target there, come back in four years.(I just changed some text)
- [x] Add more code to Judal.js and add stuff to do.
- [x] Judal Store
- [x] Turkey King
- [x] Cabbage Stand
- [x] Put changes in version 0.2 branch
- [x] Get someone to review your code once you finish

**Comment by ghost** [comment]
I need tyler to help me with arrays

**Comment by ambiguousname** [comment]
Alright. W3 Schools tutorial: [W3 Schools](http://www.w3schools.com/js/js_arrays.asp)

**Comment by ambiguousname** [comment]
You can now make more changes.

**Comment by ambiguousname** [comment]
All you need to do for the sewer quest is just change the enemy stats.

**Comment by ghost** [comment]
good job
